version: '3'
services:
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_USER=todoapp
      - POSTGRES_DB=todoapp
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
